apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://cluster1.example.com
  name: cluster1
contexts:
- context:
    cluster: cluster1
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
